/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PasteId = IDL.Nat;
export const PasteInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Paste = IDL.Record({
  'id' : PasteId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
});
export const PasteSummary = IDL.Record({
  'id' : PasteId,
  'title' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPaste' : IDL.Func([IDL.Text, IDL.Text], [PasteId], []),
  'createPasteBatch' : IDL.Func([IDL.Vec(PasteInput)], [IDL.Vec(PasteId)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaste' : IDL.Func([PasteId], [IDL.Opt(Paste)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPastes' : IDL.Func([], [IDL.Vec(PasteSummary)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PasteId = IDL.Nat;
  const PasteInput = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Paste = IDL.Record({
    'id' : PasteId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
  });
  const PasteSummary = IDL.Record({
    'id' : PasteId,
    'title' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPaste' : IDL.Func([IDL.Text, IDL.Text], [PasteId], []),
    'createPasteBatch' : IDL.Func(
        [IDL.Vec(PasteInput)],
        [IDL.Vec(PasteId)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaste' : IDL.Func([PasteId], [IDL.Opt(Paste)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPastes' : IDL.Func([], [IDL.Vec(PasteSummary)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };